// <auto-generated />
using System;
using BiteBridge.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiteBridge.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240620205221_BB7_Category_Seed_Data")]
    partial class BB7_Category_Seed_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiteBridge.Domain.Entities.Application.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Categories based on dietary restrictions and preferences.",
                            Name = "Dietary Preferences"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Meals and foods that do not contain meat.",
                            Name = "Vegetarian",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Meals and foods free from any animal products.",
                            Name = "Vegan",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Meals and foods that do not contain gluten.",
                            Name = "Gluten Free",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Meals and foods free from dairy products.",
                            Name = "Dairy Free",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Meals and foods that are low-carb and high-fat.",
                            Name = "Keto",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Foods that mimic the diet of our hunter-gatherer ancestors.",
                            Name = "Paleo",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Foods that are low in certain types of carbohydrates.",
                            Name = "Low FODMAP",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Vegetarian diet that includes seafood but excludes other meats.",
                            Name = "Pescatarian",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Foods that are permissible for Muslims to consume under Islamic law.",
                            Name = "Halal",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Foods that conform to Jewish dietary laws.",
                            Name = "Kosher",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Meals and foods that do not contain nuts or nut products.",
                            Name = "Nut Free",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Meals and foods that do not contain soy or soy products.",
                            Name = "Soy Free",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Meals and foods that do not contain added sugars.",
                            Name = "Sugar Free",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Categories based on different meal times of the day.",
                            Name = "Meal Times"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Meals typically eaten in the morning.",
                            Name = "Breakfast",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 17,
                            Description = "Meals typically eaten in the afternoon.",
                            Name = "Lunch",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 18,
                            Description = "Meals typically eaten in the evening.",
                            Name = "Dinner",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 19,
                            Description = "Categories based on different courses of a meal.",
                            Name = "Course Types"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Small dishes served before the main course.",
                            Name = "Appetizers",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 22,
                            Description = "The main dish of a meal.",
                            Name = "Main Course",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 23,
                            Description = "Sweet foods typically eaten after meals.",
                            Name = "Desserts",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 24,
                            Description = "Drinks including soft drinks, juices, and more.",
                            Name = "Beverages",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 25,
                            Description = "Categories based on different culinary traditions.",
                            Name = "Cuisines"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Dishes that blend culinary traditions from different cultures.",
                            Name = "Fusion Cuisine",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 101,
                            Description = "Local dishes specific to a particular region or country.",
                            Name = "Regional Specialties",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 26,
                            Description = "Asian cuisine including Chinese, Japanese, Thai, etc.",
                            Name = "Asian",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 36,
                            Description = "Chinese cuisine including dishes like stir-fries, dim sum, etc.",
                            Name = "Chinese",
                            ParentId = 26
                        },
                        new
                        {
                            Id = 37,
                            Description = "Japanese cuisine including sushi, ramen, etc.",
                            Name = "Japanese",
                            ParentId = 26
                        },
                        new
                        {
                            Id = 38,
                            Description = "Thai cuisine including dishes like pad Thai, green curry, etc.",
                            Name = "Thai",
                            ParentId = 26
                        },
                        new
                        {
                            Id = 39,
                            Description = "Indian cuisine including curry dishes, naan, etc.",
                            Name = "Indian",
                            ParentId = 26
                        },
                        new
                        {
                            Id = 40,
                            Description = "Korean cuisine including dishes like kimchi, bulgogi, etc.",
                            Name = "Korean",
                            ParentId = 26
                        },
                        new
                        {
                            Id = 41,
                            Description = "Vietnamese cuisine including pho, banh mi, etc.",
                            Name = "Vietnamese",
                            ParentId = 26
                        },
                        new
                        {
                            Id = 42,
                            Description = "Malaysian cuisine including laksa, nasi lemak, etc.",
                            Name = "Malaysian",
                            ParentId = 26
                        },
                        new
                        {
                            Id = 43,
                            Description = "Indonesian cuisine including nasi goreng, rendang, etc.",
                            Name = "Indonesian",
                            ParentId = 26
                        },
                        new
                        {
                            Id = 27,
                            Description = "Mexican cuisine including tacos, burritos, etc.",
                            Name = "Mexican",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 29,
                            Description = "Mediterranean cuisine including Greek, Italian, etc.",
                            Name = "Mediterranean",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 44,
                            Description = "Greek cuisine including dishes like moussaka, souvlaki, etc.",
                            Name = "Greek",
                            ParentId = 29
                        },
                        new
                        {
                            Id = 45,
                            Description = "Italian cuisine including pasta dishes, pizza, etc.",
                            Name = "Italian",
                            ParentId = 29
                        },
                        new
                        {
                            Id = 46,
                            Description = "Spanish cuisine including paella, tapas, etc.",
                            Name = "Spanish",
                            ParentId = 29
                        },
                        new
                        {
                            Id = 31,
                            Description = "French cuisine including pastries, sauces, etc.",
                            Name = "French",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 32,
                            Description = "American cuisine including burgers, BBQ, etc.",
                            Name = "American",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 33,
                            Description = "Middle Eastern cuisine including falafel, hummus, etc.",
                            Name = "Middle Eastern",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 51,
                            Description = "Lebanese cuisine including dishes like hummus, falafel, etc.",
                            Name = "Lebanese",
                            ParentId = 33
                        },
                        new
                        {
                            Id = 52,
                            Description = "Turkish cuisine including dishes like kebabs, baklava, etc.",
                            Name = "Turkish",
                            ParentId = 33
                        },
                        new
                        {
                            Id = 53,
                            Description = "Israeli cuisine including dishes like falafel, shakshuka, etc.",
                            Name = "Israeli",
                            ParentId = 33
                        },
                        new
                        {
                            Id = 54,
                            Description = "Persian cuisine including dishes like kebabs, rice dishes, etc.",
                            Name = "Persian",
                            ParentId = 33
                        },
                        new
                        {
                            Id = 55,
                            Description = "Armenian cuisine including dishes like dolma, lavash bread, etc.",
                            Name = "Armenian",
                            ParentId = 33
                        },
                        new
                        {
                            Id = 56,
                            Description = "Egyptian cuisine including dishes like koshari, falafel, etc.",
                            Name = "Egyptian",
                            ParentId = 33
                        },
                        new
                        {
                            Id = 57,
                            Description = "Iraqi cuisine including dishes like biryani, kebabs, etc.",
                            Name = "Iraqi",
                            ParentId = 33
                        },
                        new
                        {
                            Id = 58,
                            Description = "Syrian cuisine including dishes like kibbeh, fattoush, etc.",
                            Name = "Syrian",
                            ParentId = 33
                        },
                        new
                        {
                            Id = 34,
                            Description = "African cuisine including Ethiopian, Moroccan, etc.",
                            Name = "African",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 59,
                            Description = "Ethiopian cuisine including dishes like injera, doro wat, etc.",
                            Name = "Ethiopian",
                            ParentId = 34
                        },
                        new
                        {
                            Id = 60,
                            Description = "Moroccan cuisine including dishes like tagine, couscous, etc.",
                            Name = "Moroccan",
                            ParentId = 34
                        },
                        new
                        {
                            Id = 61,
                            Description = "South African cuisine including dishes like braai, bobotie, etc.",
                            Name = "South African",
                            ParentId = 34
                        },
                        new
                        {
                            Id = 62,
                            Description = "Nigerian cuisine including dishes like jollof rice, suya, etc.",
                            Name = "Nigerian",
                            ParentId = 34
                        },
                        new
                        {
                            Id = 63,
                            Description = "Ghanaian cuisine including dishes like banku, fufu, etc.",
                            Name = "Ghanaian",
                            ParentId = 34
                        },
                        new
                        {
                            Id = 64,
                            Description = "Kenyan cuisine including dishes like ugali, nyama choma, etc.",
                            Name = "Kenyan",
                            ParentId = 34
                        },
                        new
                        {
                            Id = 65,
                            Description = "Senegalese cuisine including dishes like thiéboudienne, yassa, etc.",
                            Name = "Senegalese",
                            ParentId = 34
                        },
                        new
                        {
                            Id = 66,
                            Description = "Tanzanian cuisine including dishes like pilau, ugali, etc.",
                            Name = "Tanzanian",
                            ParentId = 34
                        },
                        new
                        {
                            Id = 35,
                            Description = "South American cuisine including Brazilian, Peruvian, etc.",
                            Name = "South American",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 67,
                            Description = "Brazilian cuisine including dishes like feijoada, coxinha, etc.",
                            Name = "Brazilian",
                            ParentId = 35
                        },
                        new
                        {
                            Id = 68,
                            Description = "Peruvian cuisine including dishes like ceviche, lomo saltado, etc.",
                            Name = "Peruvian",
                            ParentId = 35
                        },
                        new
                        {
                            Id = 69,
                            Description = "Argentinian cuisine including dishes like asado, empanadas, etc.",
                            Name = "Argentinian",
                            ParentId = 35
                        },
                        new
                        {
                            Id = 70,
                            Description = "Colombian cuisine including dishes like bandeja paisa, arepas, etc.",
                            Name = "Colombian",
                            ParentId = 35
                        },
                        new
                        {
                            Id = 71,
                            Description = "Chilean cuisine including dishes like empanadas de pino, pastel de choclo, etc.",
                            Name = "Chilean",
                            ParentId = 35
                        },
                        new
                        {
                            Id = 72,
                            Description = "Ecuadorian cuisine including dishes like ceviche, encebollado, etc.",
                            Name = "Ecuadorian",
                            ParentId = 35
                        },
                        new
                        {
                            Id = 73,
                            Description = "Venezuelan cuisine including dishes like arepas, pabellón criollo, etc.",
                            Name = "Venezuelan",
                            ParentId = 35
                        },
                        new
                        {
                            Id = 74,
                            Description = "Bolivian cuisine including dishes like salteñas, pique macho, etc.",
                            Name = "Bolivian",
                            ParentId = 35
                        },
                        new
                        {
                            Id = 75,
                            Description = "Australian cuisine including iconic dishes and ingredients.",
                            Name = "Australian",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 76,
                            Description = "Categories based on different types of food.",
                            Name = "Food Types"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Various seafood dishes including fish, shrimp, etc.",
                            Name = "Seafood",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 78,
                            Description = "Italian pasta dishes including spaghetti, lasagna, etc.",
                            Name = "Pasta",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 79,
                            Description = "Different types of pizzas including Margherita, Pepperoni, etc.",
                            Name = "Pizza",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 80,
                            Description = "Various burger options including cheeseburgers, veggie burgers, etc.",
                            Name = "Burgers",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 81,
                            Description = "Healthy salad options including Caesar salad, Greek salad, etc.",
                            Name = "Salads",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 82,
                            Description = "Different soup varieties including chicken noodle soup, tomato soup, etc.",
                            Name = "Soups",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 83,
                            Description = "Various sandwich options including club sandwich, BLT, etc.",
                            Name = "Sandwiches",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 84,
                            Description = "Grilled food items including grilled chicken, grilled vegetables, etc.",
                            Name = "Grilled",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 85,
                            Description = "Different cuts of steak including ribeye, sirloin, etc.",
                            Name = "Steak",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 86,
                            Description = "Various chicken dishes including roasted chicken, chicken wings, etc.",
                            Name = "Chicken",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 87,
                            Description = "Different rice-based dishes including biryani, risotto, etc.",
                            Name = "Rice Dishes",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 88,
                            Description = "Various noodle dishes including ramen, pad Thai, etc.",
                            Name = "Noodles",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 89,
                            Description = "Japanese sushi rolls including nigiri, sashimi, etc.",
                            Name = "Sushi",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 90,
                            Description = "Mexican tacos including beef, chicken, fish tacos, etc.",
                            Name = "Tacos",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 91,
                            Description = "Various curry dishes including Indian, Thai, etc.",
                            Name = "Curries",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 92,
                            Description = "Barbecue dishes including ribs, pulled pork, brisket, etc.",
                            Name = "BBQ",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 93,
                            Description = "Chinese dim sum including dumplings, buns, spring rolls, etc.",
                            Name = "Dim Sum",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 94,
                            Description = "Spanish tapas including small plates like patatas bravas, croquettes, etc.",
                            Name = "Tapas",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 95,
                            Description = "Various steamed dishes including dim sum, steamed fish, etc.",
                            Name = "Steamed",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 96,
                            Description = "Food typically served in bars including nachos, wings, etc.",
                            Name = "Bar Food",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 97,
                            Description = "Home-style comforting dishes including mac and cheese, meatloaf, etc.",
                            Name = "Comfort Food",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 98,
                            Description = "Popular foods sold on streets including kebabs, hot dogs, etc.",
                            Name = "Street Food",
                            ParentId = 76
                        },
                        new
                        {
                            Id = 99,
                            Description = "Small, easy-to-eat foods served at parties including mini sandwiches, skewers, etc.",
                            Name = "Finger Food",
                            ParentId = 76
                        });
                });

            modelBuilder.Entity("BiteBridge.Domain.Entities.Application.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("InnerException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("BiteBridge.Domain.Entities.Application.Category", b =>
                {
                    b.HasOne("BiteBridge.Domain.Entities.Application.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BiteBridge.Domain.Entities.Application.Category", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
